name: Check Prometheus Status

on:
  push:
    branches: [ "main" ]

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: denis
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/denis/monitoring
            sudo docker compose up -d --build
            echo "=== Проверка статуса контейнеров ==="
            sudo docker compose ps
            echo "=== Проверка портов ==="
            sudo ss -tulpn | grep 9090
